//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBServiceLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyOwner
    {
        public PropertyOwner()
        {
            this.Complaints = new HashSet<Complaint>();
            this.Properties = new HashSet<Property>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int Id { get; set; }
        public string Givenname { get; set; }
        public string Surname { get; set; }
    
        public virtual ICollection<Complaint> Complaints { get; set; }
        public virtual ICollection<Property> Properties { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
